name: CustomBuoni
version: '${project.version}'
main: it.giopav.custombuoni.CustomBuoni
api-version: 1.19
authors: [ Giopav ]
description: Buoni Custom automatizzati.
commands:
  buono:
    description: Main plugin command.
    usage: §cScrivi "/buono help" per informazioni.
    permission: custombuoni.command